### ISSUE TITLE
Build ADF Code Started Giving Errors

### ISSUE THREAD

**Issue by SravanDodda** [SQLPlayer/azure.datafactory.devops#113]
Hello,
We have been using Build ADF Code for quite some time and was working great until about 4 weeks ago. It started giving error - "The property 'globalParameters' cannot be found on this object. Verify that the property exists.". We tried to resolve it modifying ARM template files to remove reference to globalParameters but to no avail

Interestingly, our ADF pipelines are NOT using any global parameters. Not sure why this error and why now

Here is the log:

2022-12-01T16:25:50.7037626Z === Validating other rules ...
2022-12-01T16:26:01.3577512Z ##[debug]Leaving D:\a\_tasks\BuildADFTask_8a00f62d-c46d-4019-9e11-c05d88821db8\1.14.1173\BuildADF.ps1.
2022-12-01T16:26:01.4093112Z ##[debug]Caught exception from task script.
2022-12-01T16:26:01.4159581Z ##[debug]Error record:
2022-12-01T16:26:01.4754218Z ##[debug]Test-AdfCode : The property 'globalParameters' cannot be found on this object. Verify that the property exists.
2022-12-01T16:26:01.4768873Z ##[debug]At D:\a\_tasks\BuildADFTask_8a00f62d-c46d-4019-9e11-c05d88821db8\1.14.1173\BuildADF.ps1:46 char:14
2022-12-01T16:26:01.4782374Z ##[debug]+ ...        $r = Test-AdfCode -RootFolder "$RootFolder" -ConfigPath $Confi ...
2022-12-01T16:26:01.4796068Z ##[debug]+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2022-12-01T16:26:01.4809370Z ##[debug]    + CategoryInfo          : NotSpecified: (:) [Test-AdfCode], PropertyNotFoundException
2022-12-01T16:26:01.4823061Z ##[debug]    + FullyQualifiedErrorId : PropertyNotFoundStrict,Test-AdfCode
2022-12-01T16:26:01.4835915Z ##[debug] 
2022-12-01T16:26:01.4857109Z ##[debug]Script stack trace:
2022-12-01T16:26:01.4894256Z ##[debug]at Test-AdfCode, D:\a\_tasks\BuildADFTask_8a00f62d-c46d-4019-9e11-c05d88821db8\1.14.1173\ps_modules\azure.datafactory.tools\public\Test-AdfCode.ps1: line 96
2022-12-01T16:26:01.4907588Z ##[debug]at <ScriptBlock>, D:\a\_tasks\BuildADFTask_8a00f62d-c46d-4019-9e11-c05d88821db8\1.14.1173\BuildADF.ps1: line 46
2022-12-01T16:26:01.4920666Z ##[debug]at <ScriptBlock>, <No file>: line 1
2022-12-01T16:26:01.4933671Z ##[debug]at <ScriptBlock>, <No file>: line 22
2022-12-01T16:26:01.4946693Z ##[debug]at <ScriptBlock>, <No file>: line 18
2022-12-01T16:26:01.4959914Z ##[debug]at <ScriptBlock>, <No file>: line 1
2022-12-01T16:26:01.4979792Z ##[debug]Exception:
2022-12-01T16:26:01.5083785Z ##[debug]System.Management.Automation.PropertyNotFoundException: The property 'globalParameters' cannot be found on this object. Verify that the property exists.
2022-12-01T16:26:01.5097213Z ##[debug]   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
2022-12-01T16:26:01.5110801Z ##[debug]   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
2022-12-01T16:26:01.5123815Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2022-12-01T16:26:01.5137240Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2022-12-01T16:26:01.5149921Z ##[debug]   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
2022-12-01T16:26:01.5162298Z ##[debug]   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
2022-12-01T16:26:01.5175288Z ##[debug]   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
2022-12-01T16:26:01.5188388Z ##[debug]   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
2022-12-01T16:26:01.5201562Z ##[debug]   at System.Management.Automation.CommandProcessorBase.Complete()
2022-12-01T16:26:01.5263290Z ##[error]The property 'globalParameters' cannot be found on this object. Verify that the property exists.
2022-12-01T16:26:01.5265312Z ##[debug]Processed: ##vso[task.logissue type=error]The property 'globalParameters' cannot be found on this object. Verify that the property exists.
2022-12-01T16:26:01.5284130Z ##[debug]Processed: ##vso[task.complete result=Failed]
2022-12-01T16:26:01.5801971Z ##[section]Finishing: Validate ADF files

Pipeline design is attached 

Could you help?
![CI Pipeline](https://user-images.githubusercontent.com/55965099/205149462-45cbb6c1-2e39-4f5e-80e0-0107902383e3.png)
![Screenshot 2022-12-01 132744](https://user-images.githubusercontent.com/55965099/205149464-e4b7bc75-3565-44b9-8b38-43a062ee43f8.png)

**Comment by NowinskiK** [comment]
I test the task in my test environment and everything looks good:
![image](https://user-images.githubusercontent.com/25029325/205354913-f27ab767-a331-43a2-8680-2b4e2453f512.png)
Can you provide ADF code in order to replicate the issue?

**Comment by SravanDodda** [comment]
> I test the task in my test environment and everything looks good: ![image](https://user-images.githubusercontent.com/25029325/205354913-f27ab767-a331-43a2-8680-2b4e2453f512.png) Can you provide ADF code in order to replicate the issue?

[Azure ADF-1.zip](https://github.com/SQLPlayer/azure.datafactory.devops/files/10143631/Azure.ADF-1.zip)

Thanks for your help

**Comment by NowinskiK** [comment]
Which one should I test?
![image](https://user-images.githubusercontent.com/25029325/205370489-5a881dfc-88b7-4cc5-b93d-08fecab26de3.png)

**Comment by SravanDodda** [comment]
> Which one should I test? ![image](https://user-images.githubusercontent.com/25029325/205370489-5a881dfc-88b7-4cc5-b93d-08fecab26de3.png)

ADF-BIGroupFacts01-Dev

**Comment by SravanDodda** [comment]
I am sorry, it should be "Azure ADF". When I publish ADF, ARM templates are getting updated in "ADF-BIGroupFacts01-Dev" and pipelines are getting updated in "Azure ADF". "ADF-BIGroupFacts01-Dev" is our development ADF name. Git is configured in ADF for collaboration and deploy branch to "Dev" branch in Azure DevOps

Does it make sense?

**Comment by NowinskiK** [comment]
For both folders the same issue raises:
![image](https://user-images.githubusercontent.com/25029325/205374494-f4c0159e-caf0-4574-8ad5-1c2b5d452f76.png)

**Comment by SravanDodda** [comment]
Yes, this duplication thing is new. Even before the duplication thing, "globalParameters" issue was happening.

![Previous Error](https://user-images.githubusercontent.com/55965099/205375853-337059c2-7d09-481a-98ad-0a2ffd431767.png)

**Comment by NowinskiK** [comment]
The duplication is because you have the same name for a pipeline as well as dataflow.
But that does not cause the error.

**Comment by SravanDodda** [comment]
Correct. I just realized that while going through Data Flows and Pipelines

So, you are not able to reproduce the 'globalParameter" error?

**Comment by NowinskiK** [comment]
I reproduced the error thanks to the attached code.
I will be released in PS module first (ver.0.110), and in DevOps extension afterwards (tonight).

**Comment by NowinskiK** [comment]
Fixed in **ver.1.15.1239**, just released.

**Comment by SravanDodda** [comment]
> Fixed in **ver.1.15.1239**, just released.

Thank you. Appreciate your help

How do I install the new version by replacing the existing one? Could you provide some documentation of how to do that?

**Comment by NowinskiK** [comment]
It should be installed automatically.

**Comment by SravanDodda** [comment]
> It should be installed automatically.

Thank you. Now I get this and failing. Could you help?

![NewError](https://user-images.githubusercontent.com/55965099/205455660-2e15ad74-257e-4688-9638-f2e2beab77a2.png)

**Comment by NowinskiK** [comment]
You can not point ARM Template parameter file as a config.
This task is not for deploying from ARM Template but from adf code directly.
Ready more in documentation and watch video on my YouTube channel:
https://sqlplayer.net/adftools

**Comment by SravanDodda** [comment]
> You can not point ARM Template parameter file as a config. This task is not for deploying from ARM Template but from adf code directly. Read more in documentation and watch video on my YouTube channel: https://sqlplayer.net/adftools

Got it. Thank you so much for your great help and taking care of this in no time. Really appreciate it and am a big follower on YouTube as well
